from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from .schemas import AIResponse, InsightLevel, Metadata
from .router import route_query
from .rag import VectorStore
from .security import SecurityLayer
import time
import logging
import os
import json

# --- Setup Observability ---
logging.basicConfig(level=logging.INFO, format='%(asctime)s | %(levelname)s | %(message)s')
logger = logging.getLogger("quant-platform.engine")

app = FastAPI(title="quant-platform Engine")

# --- Real Services ---
# RAG store URI. Defaults to a local on-disk index (safe for the ai-engine's restricted network).
# `POSTGRES_URL` is supported for backward compatibility but not required.
RAG_STORE_URI = os.getenv("RAG_STORE_URI") or os.getenv("POSTGRES_URL") or "local://"
rag_store = None
groq_client = None
security = SecurityLayer()

def get_rag_store() -> VectorStore:
    global rag_store
    if rag_store is None:
        rag_store = VectorStore(connection_string=RAG_STORE_URI)
    return rag_store

def get_groq_client():
    global groq_client
    if groq_client is None:
        # Import lazily to keep unit tests lightweight and avoid hard dependency at import time.
        from groq import Groq
        groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    return groq_client

def select_groq_model(level: InsightLevel) -> str:
    if level == InsightLevel.DEEP:
        return "llama3-70b-8192"  # Powerful proxy for deep reasoning
    return "llama3-8b-8192"

def retrieve_context_and_citations(query: str, user_id: str, level: InsightLevel):
    context_chunks = []
    citations = []
    if level in [InsightLevel.STANDARD, InsightLevel.DEEP]:
        try:
            if level == InsightLevel.DEEP:
                k = int(os.getenv("RAG_K_DEEP", "6"))
                deep = True
            else:
                k = int(os.getenv("RAG_K_STANDARD", "4"))
                deep = False

            raw_results = get_rag_store().retrieve(query, user_id=user_id, k=k, deep=deep)
            context_chunks = [r[0] for r in raw_results]
            for chunk_text, meta in raw_results:
                citations.append({
                    "source": meta.get("source", "Unknown"),
                    "title": meta.get("title", "Doc"),
                    "url": meta.get("url"),
                    "chunk": chunk_text[:100] + "..."
                })
        except Exception as e:
            logger.error(f"RAG Error: {e}")
    return context_chunks, citations

def run_llm(safe_prompt: str, level: InsightLevel):
    groq_model = select_groq_model(level)
    reasoning = None
    summary = ""
    try:
        chat_completion = get_groq_client().chat.completions.create(
            messages=[
                {"role": "system", "content": "You are a helpful financial AI."},
                {"role": "user", "content": safe_prompt}
            ],
            model=groq_model,
        )
        full_text = chat_completion.choices[0].message.content
        summary = full_text
        if level == InsightLevel.DEEP:
            reasoning = "Generated by Groq."
    except Exception as e:
        logger.error(f"LLM Error: {e}")
        summary = "Error generating insight."
        if level == InsightLevel.DEEP and not reasoning:
            # Deep responses must include a non-null `reasoning` per contract.
            # Do not leak stack traces or secret config; keep this high-level.
            reasoning = f"LLM unavailable ({type(e).__name__})."
    return summary, reasoning, groq_model

def format_sse(event: str, data):
    payload = json.dumps({"event": event, "data": data})
    # SSE requires *actual* newlines between events.
    return f"data: {payload}\n\n"

@app.post("/insights", response_model=AIResponse)
async def generate_insights(query: str, user_id: str):
    start_time = time.time()
    
    # 1. Route
    level, _ = route_query(query)
    
    # 2. RAG Retrieval
    context_chunks, citations = retrieve_context_and_citations(query, user_id, level)

    # 3. Security & Prompt Construction
    system_instruction = "Provide a market insight summary."
    if level == InsightLevel.DEEP:
        system_instruction += " Use strict reasoning chains. Analyze the user's query deeply."
        
    safe_prompt = security.construct_prompt(
        system_instruction=system_instruction,
        user_query=query,
        context_docs=context_chunks
    )

    # 4. LLM Generation (Real Groq)
    summary, reasoning, groq_model = run_llm(safe_prompt, level)

    # 5. Observability & Response
    latency = int((time.time() - start_time) * 1000)
    
    logger.info(f"event=insight_generated user={user_id} level={level} model={groq_model} latency={latency}ms rag_hits={len(citations)}")
    
    return AIResponse(
        level=level,
        summary=summary,
        insights=[],
        reasoning=reasoning,
        calculations=[],
        citations=citations,
        metadata=Metadata(
            model=groq_model,
            latency_ms=latency,
            cached=False
        )
    )

@app.get("/stream/insights")
async def stream_insights(query: str, user_id: str):
    def event_generator():
        start_time = time.time()
        level, _ = route_query(query)

        yield format_sse("meta", {"level": level, "status": "started"})

        context_chunks, citations = retrieve_context_and_citations(query, user_id, level)

        system_instruction = "Provide a market insight summary."
        if level == InsightLevel.DEEP:
            system_instruction += " Use strict reasoning chains. Analyze the user's query deeply."

        safe_prompt = security.construct_prompt(
            system_instruction=system_instruction,
            user_query=query,
            context_docs=context_chunks
        )

        summary, reasoning, groq_model = run_llm(safe_prompt, level)
        latency = int((time.time() - start_time) * 1000)

        yield format_sse("summary", {
            "level": level,
            "summary": summary,
            "reasoning": reasoning,
            "citations": citations,
            "metadata": {
                "model": groq_model,
                "latency_ms": latency,
                "cached": False
            }
        })

        logger.info(
            f"event=insight_streamed user={user_id} level={level} model={groq_model} "
            f"latency={latency}ms rag_hits={len(citations)}"
        )

    return StreamingResponse(event_generator(), media_type="text/event-stream")

@app.get("/health")
def health_check():
    return {"status": "ok", "version": "0.3.0"}
