import type { Metadata } from "next";
import Link from "next/link";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({
  title: "Terms of Service",
  description: "Terms and conditions for using the QuantPlatform platform.",
  canonical: "/terms",
});

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="max-w-[900px] mx-auto px-6 py-14 space-y-10">
        <header className="space-y-3">
          <p className="text-xs uppercase tracking-[0.3em] text-muted">
            Terms of Service
          </p>
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight">
            Terms and conditions
          </h1>
          <p className="text-sm text-muted leading-relaxed">
            Last updated: February 2026. By accessing or using QuantPlatform, you
            agree to be bound by these terms.
          </p>
        </header>

        <section className="space-y-4">
          <h2 className="text-lg font-bold tracking-tight">
            1. Acceptance of terms
          </h2>
          <div className="rounded-2xl border border-border-color bg-surface p-5">
            <p className="text-sm leading-relaxed text-muted">
              By creating an account or using the QuantPlatform platform, you agree
              to these Terms of Service and our Privacy Policy. If you do not
              agree, you must not use the service.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold tracking-tight">
            2. Description of service
          </h2>
          <div className="rounded-2xl border border-border-color bg-surface p-5">
            <p className="text-sm leading-relaxed text-muted">
              QuantPlatform provides AI-powered market research tools including
              watchlist generation, risk analysis, market overviews, and stock
              data aggregation. The platform is intended for informational and
              educational purposes only.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold tracking-tight">
            3. Not financial advice
          </h2>
          <div className="rounded-2xl border border-border-color bg-surface p-5">
            <p className="text-sm leading-relaxed text-muted">
              Content generated by QuantPlatform, including AI syntheses, risk
              scores, and market analyses, does not constitute financial,
              investment, tax, or legal advice. You should not rely on any
              output from the platform as a basis for making investment
              decisions. Always consult a qualified financial advisor before
              making investment decisions.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold tracking-tight">
            4. User accounts
          </h2>
          <div className="rounded-2xl border border-border-color bg-surface p-5 space-y-3">
            <ul className="text-sm text-muted list-disc pl-5 space-y-2">
              <li>You must provide accurate information when creating an account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must not share your account or use another person's account.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
            </ul>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold tracking-tight">
            5. Acceptable use
          </h2>
          <div className="rounded-2xl border border-border-color bg-surface p-5 space-y-3">
            <p className="text-sm leading-relaxed text-muted">
              You agree not to:
            </p>
            <ul className="text-sm text-muted list-disc pl-5 space-y-2">
              <li>Use the service for any unlawful purpose.</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the platform beyond normal use.</li>
              <li>Submit prompts designed to manipulate, exploit, or extract system instructions from the AI engine.</li>
              <li>Interfere with the operation or security of the service.</li>
              <li>Resell or redistribute content generated by the platform without permission.</li>
            </ul>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold tracking-tight">
            6. Intellectual property
          </h2>
          <div className="rounded-2xl border border-border-color bg-surface p-5">
            <p className="text-sm leading-relaxed text-muted">
              The QuantPlatform platform, including its design, code, and branding,
              is owned by QuantPlatform. AI-generated content is provided for your
              personal use. Market data is sourced from third-party providers
              and is subject to their respective terms.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold tracking-tight">
            7. Limitation of liability
          </h2>
          <div className="rounded-2xl border border-border-color bg-surface p-5">
            <p className="text-sm leading-relaxed text-muted">
              QuantPlatform is provided on an "as is" and "as available" basis. We
              make no warranties regarding the accuracy, completeness, or
              reliability of any content or analysis. To the maximum extent
              permitted by law, QuantPlatform shall not be liable for any indirect,
              incidental, or consequential damages arising from your use of the
              platform.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold tracking-tight">
            8. Changes to terms
          </h2>
          <div className="rounded-2xl border border-border-color bg-surface p-5">
            <p className="text-sm leading-relaxed text-muted">
              We may update these terms from time to time. Continued use of the
              platform after changes constitutes acceptance of the revised
              terms. We will notify users of material changes via the platform
              or email.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-lg font-bold tracking-tight">Contact</h2>
          <div className="rounded-2xl border border-border-color bg-surface p-5">
            <p className="text-sm leading-relaxed text-muted">
              For questions about these terms, contact{" "}
              <a
                href="mailto:support@quant-platform.com"
                className="text-foreground font-semibold underline-offset-4 hover:underline"
              >
                support@quant-platform.com
              </a>
              .
            </p>
          </div>
        </section>

        <div className="pt-4 border-t border-border-color">
          <Link
            href="/"
            className="text-xs text-muted hover:text-foreground transition-colors"
          >
            Back to home
          </Link>
        </div>
      </div>
    </main>
  );
}
